# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xci
# IP: The module: 'system_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xci
# IP: The module: 'system_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab04/Lab4-1/vivado_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
