set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports { led[0] }]; #IO_L6N_T0_VREF_34 Sch=led[0]
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports { led[1] }]; #IO_L6P_T0_34 Sch=led[1]
set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports { led[2] }]; #IO_L21N_T3_DQS_AD14N_35 Sch=led[2]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { led[3] }]; #IO_L23P_T3_35 Sch=led[3]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg0[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[1]}]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/cmd_done]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[6]}]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/s00_axi_aresetn]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[5]}]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in_valid]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_valid]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[6]}]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_w_enable]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[5]}]

set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[2]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg0[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/cmd_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_w_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/s00_axi_aresetn]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
