# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/processor/processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor || ORIG_REF_NAME==processor} -quiet] -quiet

# IP: bd/processor/ip/processor_processing_system7_0_0/processor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_processing_system7_0_0 || ORIG_REF_NAME==processor_processing_system7_0_0} -quiet] -quiet

# XDC: bd/processor/processor_ooc.xdc
