# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Leo/Desktop/FPGA/hw5/hw5.srcs/sources_1/bd/hw5/ip/hw5_parity_0_1/hw5_parity_0_1.xci
# IP: The module: 'hw5_parity_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leo/Desktop/FPGA/hw5/hw5.srcs/sources_1/bd/hw5/ip/hw5_parity_0_1/src/parity_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw5_parity_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Leo/Desktop/FPGA/hw5/hw5.srcs/sources_1/bd/hw5/ip/hw5_parity_0_1/hw5_parity_0_1.xci
# IP: The module: 'hw5_parity_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Leo/Desktop/FPGA/hw5/hw5.srcs/sources_1/bd/hw5/ip/hw5_parity_0_1/src/parity_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw5_parity_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
