# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/123NCKU/FPGA/Lab6_HW/Lab6_HW.srcs/sources_1/bd/design_1/ip/design_1_Matrix_Processor_3X3_0_0/design_1_Matrix_Processor_3X3_0_0.xci
# IP: The module: 'design_1_Matrix_Processor_3X3_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/123NCKU/FPGA/Lab6_HW/Lab6_HW.srcs/sources_1/bd/design_1/ip/design_1_Matrix_Processor_3X3_0_0/src/Matrix_Processor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Matrix_Processor_3X3_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/123NCKU/FPGA/Lab6_HW/Lab6_HW.srcs/sources_1/bd/design_1/ip/design_1_Matrix_Processor_3X3_0_0/design_1_Matrix_Processor_3X3_0_0.xci
# IP: The module: 'design_1_Matrix_Processor_3X3_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/123NCKU/FPGA/Lab6_HW/Lab6_HW.srcs/sources_1/bd/design_1/ip/design_1_Matrix_Processor_3X3_0_0/src/Matrix_Processor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Matrix_Processor_3X3_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
