# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ldap-users/shiyong/Downloads/FPGA/pynq-z2_v1.0.xdc

# Block Designs: bd/design_timer/design_timer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer || ORIG_REF_NAME==design_timer}]

# IP: bd/design_timer/ip/design_timer_processing_system7_0_0/design_timer_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_processing_system7_0_0 || ORIG_REF_NAME==design_timer_processing_system7_0_0}]

# IP: bd/design_timer/ip/design_timer_axi_gpio_0_0/design_timer_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_axi_gpio_0_0 || ORIG_REF_NAME==design_timer_axi_gpio_0_0}]

# IP: bd/design_timer/ip/design_timer_ps7_0_axi_periph_1/design_timer_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_timer_ps7_0_axi_periph_1}]

# IP: bd/design_timer/ip/design_timer_rst_ps7_0_100M_1/design_timer_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_rst_ps7_0_100M_1 || ORIG_REF_NAME==design_timer_rst_ps7_0_100M_1}]

# IP: bd/design_timer/ip/design_timer_axi_timer_0_0/design_timer_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_axi_timer_0_0 || ORIG_REF_NAME==design_timer_axi_timer_0_0}]

# IP: bd/design_timer/ip/design_timer_xbar_0/design_timer_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_xbar_0 || ORIG_REF_NAME==design_timer_xbar_0}]

# IP: bd/design_timer/ip/design_timer_axi_gpio_1_0/design_timer_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_axi_gpio_1_0 || ORIG_REF_NAME==design_timer_axi_gpio_1_0}]

# IP: bd/design_timer/ip/design_timer_axi_gpio_2_0/design_timer_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_axi_gpio_2_0 || ORIG_REF_NAME==design_timer_axi_gpio_2_0}]

# IP: bd/design_timer/ip/design_timer_axi_gpio_3_0/design_timer_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_axi_gpio_3_0 || ORIG_REF_NAME==design_timer_axi_gpio_3_0}]

# IP: bd/design_timer/ip/design_timer_auto_pc_0/design_timer_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_timer_auto_pc_0 || ORIG_REF_NAME==design_timer_auto_pc_0}]

# XDC: bd/design_timer/design_timer_ooc.xdc
