# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/user/Documents/GitHub/F84051053/xdc/pynq-z2_v1.0.xdc

# Block Designs: bd/hw5/hw5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5 || ORIG_REF_NAME==hw5} -quiet] -quiet

# IP: bd/hw5/ip/hw5_pwm_0_0/hw5_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_pwm_0_0 || ORIG_REF_NAME==hw5_pwm_0_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_arithmetic_0_0/hw5_arithmetic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_arithmetic_0_0 || ORIG_REF_NAME==hw5_arithmetic_0_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_parity_0_0/hw5_parity_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_parity_0_0 || ORIG_REF_NAME==hw5_parity_0_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_hash_0_0/hw5_hash_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_hash_0_0 || ORIG_REF_NAME==hw5_hash_0_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_sorting_0_0/hw5_sorting_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_sorting_0_0 || ORIG_REF_NAME==hw5_sorting_0_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_processing_system7_0_0/hw5_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_processing_system7_0_0 || ORIG_REF_NAME==hw5_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_ps7_0_axi_periph_0/hw5_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw5_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_rst_ps7_0_100M_0/hw5_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_rst_ps7_0_100M_0 || ORIG_REF_NAME==hw5_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_xbar_0/hw5_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_xbar_0 || ORIG_REF_NAME==hw5_xbar_0} -quiet] -quiet

# IP: bd/hw5/ip/hw5_auto_pc_0/hw5_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw5_auto_pc_0 || ORIG_REF_NAME==hw5_auto_pc_0} -quiet] -quiet

# XDC: bd/hw5/hw5_ooc.xdc
