# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.cache/wt [current_project]
set_property parent.project_path C:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/user/Documents/GitHub/F84051053/hw5/ip_repo/pwm_1.0
  c:/Users/user/Documents/GitHub/F84051053/hw5/ip_repo/parity_1.0
  c:/Users/user/Documents/GitHub/F84051053
  c:/Users/user/Documents/GitHub/F84051053/hw5/ip_repo/arithmetic_1.0
  c:/Users/user/Documents/GitHub/F84051053/hw5/ip_repo/sorting_1.0
  c:/Users/user/Documents/GitHub/F84051053/hw5/ip_repo/hash_1.0
  c:/Users/user/Documents/GitHub/F84051053/hw5/ip_repo
  c:/Users/user/Documents/GitHub/F84051053/hw5/ip_repo/pwm_1.0
} [current_project]
set_property ip_output_repo c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/hdl/hw5_wrapper.v
add_files C:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/hw5.bd
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/xdc/pwm_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/xdc/arithmetic_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/xdc/parity_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/xdc/hash_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/xdc/sorting_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_processing_system7_0_0/hw5_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_rst_ps7_0_100M_0/hw5_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_rst_ps7_0_100M_0/hw5_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_rst_ps7_0_100M_0/hw5_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_xbar_0/hw5_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_auto_pc_0/hw5_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/hw5_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/Documents/GitHub/F84051053/xdc/pynq-z2_v1.0.xdc
set_property used_in_implementation false [get_files C:/Users/user/Documents/GitHub/F84051053/xdc/pynq-z2_v1.0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top hw5_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hw5_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hw5_wrapper_utilization_synth.rpt -pb hw5_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
