webtalk_init -webtalk_dir C:\\Users\\ruyuan\\Desktop\\FPGA_Design-master\\Lab05\\hw\\project_8\\project_8.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-11-30 20:29:18" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211595118_0_0_835" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6k10q4u9k1vb76roi7hh823h1m" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_19" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.452 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1543578697867" -context "sdk\\\\bsp/1543578697867"
webtalk_add_data -client sdk -key hwid -value "1543576605962" -context "sdk\\\\bsp/1543578697867"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1543578697867"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1543578697867"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1543578697867"
webtalk_add_data -client sdk -key uid -value "1543578700670" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key hwid -value "1543576605962" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key bspid -value "1543578697867" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key projSize -value "827.08984375" -context "sdk\\\\application/1543578700670"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1543580958928"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1543580958928"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1543580958928"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1543580958928"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1543580958928"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1543580958928"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1543580958928"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1543580958928"
webtalk_transmit -clientid 380285833 -regid "211595118_0_0_835" -xml C:\\Users\\ruyuan\\Desktop\\FPGA_Design-master\\Lab05\\hw\\project_8\\project_8.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\ruyuan\\Desktop\\FPGA_Design-master\\Lab05\\hw\\project_8\\project_8.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\ruyuan\\Desktop\\FPGA_Design-master\\Lab05\\hw\\project_8\\project_8.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
