# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab03/Lab3-2/vivado_prj/vivado_prj.srcs/sources_1/bd/led_ctrl/ip/led_ctrl_auto_pc_0/led_ctrl_auto_pc_0.xci
# IP: The module: 'led_ctrl_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab03/Lab3-2/vivado_prj/vivado_prj.srcs/sources_1/bd/led_ctrl/ip/led_ctrl_auto_pc_0/led_ctrl_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_ctrl_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab03/Lab3-2/vivado_prj/vivado_prj.srcs/sources_1/bd/led_ctrl/ip/led_ctrl_auto_pc_0/led_ctrl_auto_pc_0.xci
# IP: The module: 'led_ctrl_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab03/Lab3-2/vivado_prj/vivado_prj.srcs/sources_1/bd/led_ctrl/ip/led_ctrl_auto_pc_0/led_ctrl_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_ctrl_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
