# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ruyuan/Desktop/FPGA_Design-master/Lab05/hw/project_8/project_8.srcs/sources_1/bd/design_1/ip/design_1_alu_0_0/design_1_alu_0_0.xci
# IP: The module: 'design_1_alu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ruyuan/Desktop/FPGA_Design-master/Lab05/hw/project_8/project_8.srcs/sources_1/bd/design_1/project_2/alu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_alu_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/ruyuan/Desktop/FPGA_Design-master/Lab05/hw/project_8/project_8.srcs/sources_1/bd/design_1/ip/design_1_alu_0_0/design_1_alu_0_0.xci
# IP: The module: 'design_1_alu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ruyuan/Desktop/FPGA_Design-master/Lab05/hw/project_8/project_8.srcs/sources_1/bd/design_1/project_2/alu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_alu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
