# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab02/Lab2-2/xdc/pynq-z2_v1.0.xdc

# XDC: C:/Users/VLSILAB/Documents/GitHub/FPGA_Design/Lab02/Lab2-2/xdc/top.xdc

# Block Designs: bd/blinky_bd/blinky_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinky_bd || ORIG_REF_NAME==blinky_bd} -quiet] -quiet

# IP: bd/blinky_bd/ip/blinky_bd_divider_0_0/blinky_bd_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinky_bd_divider_0_0 || ORIG_REF_NAME==blinky_bd_divider_0_0} -quiet] -quiet

# IP: bd/blinky_bd/ip/blinky_bd_blinky_0_0/blinky_bd_blinky_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinky_bd_blinky_0_0 || ORIG_REF_NAME==blinky_bd_blinky_0_0} -quiet] -quiet

# XDC: bd/blinky_bd/blinky_bd_ooc.xdc
