webtalk_init -webtalk_dir D:\\123NCKU\\FPGA\\Lab6_HW\\Lab6_HW.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-12-09 00:57:27" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aknirdllak1gv62bqo40ihfehd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2694 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.091 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1544279734041" -context "sdk\\\\bsp/1544279734041"
webtalk_add_data -client sdk -key hwid -value "1544272862433" -context "sdk\\\\bsp/1544279734041"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1544279734041"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1544279734041"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1544279734041"
webtalk_add_data -client sdk -key uid -value "1544279735306" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key hwid -value "1544272862433" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key bspid -value "1544279734041" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key projSize -value "594.6953125" -context "sdk\\\\application/1544279735306"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1544288247210"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1544288247210"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1544288247210"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1544288247210"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1544288247210"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1544288247210"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1544288247210"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1544288247210"
webtalk_transmit -clientid 1979837323 -regid "" -xml D:\\123NCKU\\FPGA\\Lab6_HW\\Lab6_HW.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\123NCKU\\FPGA\\Lab6_HW\\Lab6_HW.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\123NCKU\\FPGA\\Lab6_HW\\Lab6_HW.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
