# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ldap-users/shiyong/Downloads/FPGA/Timer/Timer.srcs/sources_1/bd/design_timer/ip/design_timer_xbar_0/design_timer_xbar_0.xci
# IP: The module: 'design_timer_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ldap-users/shiyong/Downloads/FPGA/Timer/Timer.srcs/sources_1/bd/design_timer/ip/design_timer_xbar_0/design_timer_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_timer_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/ldap-users/shiyong/Downloads/FPGA/Timer/Timer.srcs/sources_1/bd/design_timer/ip/design_timer_xbar_0/design_timer_xbar_0.xci
# IP: The module: 'design_timer_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ldap-users/shiyong/Downloads/FPGA/Timer/Timer.srcs/sources_1/bd/design_timer/ip/design_timer_xbar_0/design_timer_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_timer_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
