# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_parity_0_0/hw5_parity_0_0.xci
# IP: The module: 'hw5_parity_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/xdc/parity_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw5_parity_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/hw5/ip/hw5_parity_0_0/hw5_parity_0_0.xci
# IP: The module: 'hw5_parity_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Documents/GitHub/F84051053/hw5/hw5_pj/hw5_pj.srcs/sources_1/bd/xdc/parity_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw5_parity_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
