# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/user/Documents/GitHub/External_hw/hw3/hw/Lab3-2/xdc/pynq-z2_v1.0.xdc

# Block Designs: bd/led_ctrl/led_ctrl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl || ORIG_REF_NAME==led_ctrl} -quiet] -quiet

# IP: bd/led_ctrl/ip/led_ctrl_processing_system7_0_0/led_ctrl_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl_processing_system7_0_0 || ORIG_REF_NAME==led_ctrl_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_ctrl/ip/led_ctrl_axi_gpio_0_0/led_ctrl_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl_axi_gpio_0_0 || ORIG_REF_NAME==led_ctrl_axi_gpio_0_0} -quiet] -quiet

# IP: bd/led_ctrl/ip/led_ctrl_axi_gpio_1_0/led_ctrl_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl_axi_gpio_1_0 || ORIG_REF_NAME==led_ctrl_axi_gpio_1_0} -quiet] -quiet

# IP: bd/led_ctrl/ip/led_ctrl_ps7_0_axi_periph_0/led_ctrl_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl_ps7_0_axi_periph_0 || ORIG_REF_NAME==led_ctrl_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/led_ctrl/ip/led_ctrl_rst_ps7_0_100M_0/led_ctrl_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl_rst_ps7_0_100M_0 || ORIG_REF_NAME==led_ctrl_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/led_ctrl/ip/led_ctrl_xbar_0/led_ctrl_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl_xbar_0 || ORIG_REF_NAME==led_ctrl_xbar_0} -quiet] -quiet

# IP: bd/led_ctrl/ip/led_ctrl_auto_pc_0/led_ctrl_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ctrl_auto_pc_0 || ORIG_REF_NAME==led_ctrl_auto_pc_0} -quiet] -quiet

# XDC: bd/led_ctrl/led_ctrl_ooc.xdc
