set_property SRC_FILE_INFO {cfile:D:/123NCKU/FPGA/Lab6_HW/Lab6_HW.srcs/constrs_1/new/constraint.xdc rfile:../../../Lab6_HW.srcs/constrs_1/new/constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports { led[0] }]; #IO_L6N_T0_VREF_34 Sch=led[0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports { led[1] }]; #IO_L6P_T0_34 Sch=led[1]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports { led[2] }]; #IO_L21N_T3_DQS_AD14N_35 Sch=led[2]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { led[3] }]; #IO_L23P_T3_35 Sch=led[3]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[4]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[5]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[7]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[3]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[2]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[5]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[7]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[3]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[5]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[2]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[1]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[6]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[0]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[2]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg0[0]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[1]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/cmd_done]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[2]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[7]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[0]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[4]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[6]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[7]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[4]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[0]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[3]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[5]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[3]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[6]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[1]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[4]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[6]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/s00_axi_aresetn]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[7]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[6]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[6]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[4]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[6]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[1]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[2]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[5]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[3]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[3]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[2]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[3]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[7]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[0]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[4]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[1]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[1]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[4]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[5]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in_valid]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[6]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[7]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[3]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[4]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_reg_n_0_[0]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[1]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[5]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[2]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[0]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[2]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[5]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[7]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_valid]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[0]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[2]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[3]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[6]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[5]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[6]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[0]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[1]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[2]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[6]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_w_enable]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[0]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[7]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[1]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[7]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[1]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[5]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[0]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[7]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[3]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[4]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[2]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[4]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[3]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[4]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[5]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[3]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[2]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[0]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/led[1]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[0]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[1]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[2]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_in[7]}]]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_out[7]}]]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in[7]}]]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/state[2]}]]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_out[7]}]]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_d_in[7]}]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_in[7]}]]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/data_out[7]}]]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg0[0]}]]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg2[7]}]]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg3[7]}]]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[0]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[1]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[2]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[3]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[4]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[5]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[6]} {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/slv_reg1[7]}]]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/cmd_done]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_addr_reg_n_0_[0]}]]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/mem_w_enable]]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[1]}]]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[2]}]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[3]}]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[4]}]]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[5]}]]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[6]}]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_addr_reg_n_0_[7]}]]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_cmd_valid]]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/top_ctrl1/pro_d_in_valid]]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/Matrix_Processor_3X3_0/inst/Matrix_Processor_3X3_v1_0_S00_AXI_inst/s00_axi_aresetn]]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
